services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/web
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_PUBLIC_POSTHOG_KEY=${VITE_PUBLIC_POSTHOG_KEY}
        - VITE_PUBLIC_POSTHOG_HOST=${VITE_PUBLIC_POSTHOG_HOST}
    env_file:
      - ./frontend/web/.env
    ports:
      - "80:80"
    depends_on:
      - backend
