services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RUN_MIGRATION=true
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/web
    env_file:
      - ./frontend/web/.env
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
