"""fix_restaurant_schedule_id_name

Revision ID: 0c0135683609
Revises: d78cf049bf2e
Create Date: 2026-05-25 20:36:31.122948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0135683609'
down_revision: Union[str, Sequence[str], None] = 'd78cf049bf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_schedules', sa.Column('restaurant_schedule_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('restaurant_schedules', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_schedules', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('restaurant_schedules', 'restaurant_schedule_id')
    # ### end Alembic commands ###
