"""Add description to restaurant

Revision ID: 269f62d8a9e5
Revises: ed32c8bedca3
Create Date: 2026-03-29 15:17:19.677072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269f62d8a9e5'
down_revision: Union[str, Sequence[str], None] = 'ed32c8bedca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'description')
    # ### end Alembic commands ###
