"""split_adress_and_add_schedule

Revision ID: d78cf049bf2e
Revises: b7ef3864335c
Create Date: 2026-05-25 16:06:35.743295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78cf049bf2e'
down_revision: Union[str, Sequence[str], None] = 'b7ef3864335c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week_enum'), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('restaurant', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('restaurant', sa.Column('street', sa.String(length=150), nullable=False))
    op.add_column('restaurant', sa.Column('building_number', sa.String(length=20), nullable=False))
    op.add_column('restaurant', sa.Column('postal_code', sa.String(length=20), nullable=False))
    op.add_column('restaurant', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.drop_column('restaurant', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('restaurant', 'phone_number')
    op.drop_column('restaurant', 'postal_code')
    op.drop_column('restaurant', 'building_number')
    op.drop_column('restaurant', 'street')
    op.drop_column('restaurant', 'city')
    op.drop_table('restaurant_schedules')
    # ### end Alembic commands ###
