"""change_qr_code_token_to_uuid

Revision ID: e36f05321b5b
Revises: 269f62d8a9e5
Create Date: 2026-04-12 15:05:44.178055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36f05321b5b'
down_revision: Union[str, Sequence[str], None] = '269f62d8a9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_table', 'qr_code_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Uuid(),
               postgresql_using='qr_code_token::uuid',
               existing_nullable=False)
    op.drop_constraint(op.f('restaurant_table_qr_code_token_key'), 'restaurant_table', type_='unique')
    op.create_index(op.f('ix_restaurant_table_qr_code_token'), 'restaurant_table', ['qr_code_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_table_qr_code_token'), table_name='restaurant_table')
    op.create_unique_constraint(op.f('restaurant_table_qr_code_token_key'), 'restaurant_table', ['qr_code_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('restaurant_table', 'qr_code_token',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=255),
               postgresql_using='qr_code_token::varchar',
               existing_nullable=False)
    # ### end Alembic commands ###
