"""Init

Revision ID: ed32c8bedca3
Revises: 
Create Date: 2026-03-28 18:12:59.954043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed32c8bedca3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'WAITER', 'CUSTOMER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('has_kiosk', sa.Boolean(), nullable=False),
    sa.Column('cuisine', sa.Enum('ITALIAN', 'AMERICAN', 'POLISH', 'MEDITERRANEAN', 'GREEK', 'FRENCH', 'SPANISH', 'ASIAN', 'JAPANESE', 'INDIAN', 'KEBAB', 'MEXICAN', 'VEGAN', 'FUSION', 'OTHER', name='cuisine_type_enum'), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('menu_item',
    sa.Column('menu_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price >= 0', name='chk_menu_item_price_non_negative'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id'),
    sa.UniqueConstraint('menu_item_id', 'restaurant_id', name='uq_menu_item_id_restaurant')
    )
    op.create_table('restaurant_table',
    sa.Column('table_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('qr_code_token', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'OCCUPIED', 'RESERVED', name='table_status_enum'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='chk_restaurant_table_capacity_positive'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('qr_code_token'),
    sa.UniqueConstraint('restaurant_id', 'table_number', name='uq_restaurant_table_number'),
    sa.UniqueConstraint('table_id', 'restaurant_id', name='uq_restaurant_table_id_restaurant')
    )
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELED', name='reservation_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id', 'restaurant_id'], ['restaurant_table.table_id', 'restaurant_table.restaurant_id'], name='fk_reservation_table_same_restaurant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('reservation_id', 'restaurant_id', name='uq_reservation_id_restaurant')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('order_source', sa.Enum('KIOSK', 'WEB_APP', 'QR_TABLE', name='order_source_enum'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PAID', 'IN_PREPARATION', 'READY', 'CANCELED', name='order_status_enum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("user_id IS NOT NULL OR table_id IS NOT NULL OR reservation_id IS NOT NULL OR order_source = 'KIOSK'", name='chk_order_origin_present'),
    sa.CheckConstraint('total_amount >= 0', name='chk_order_total_non_negative'),
    sa.ForeignKeyConstraint(['reservation_id', 'restaurant_id'], ['reservation.reservation_id', 'reservation.restaurant_id'], name='fk_order_reservation_same_restaurant', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id', 'restaurant_id'], ['restaurant_table.table_id', 'restaurant_table.restaurant_id'], name='fk_order_table_same_restaurant', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_id', 'restaurant_id', name='uq_order_id_restaurant')
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customization_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_order_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='chk_order_item_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['menu_item_id', 'restaurant_id'], ['menu_item.menu_item_id', 'menu_item.restaurant_id'], name='fk_order_item_menu_item_same_restaurant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id', 'restaurant_id'], ['order.order_id', 'order.restaurant_id'], name='fk_order_item_order_same_restaurant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('order')
    op.drop_table('reservation')
    op.drop_table('restaurant_table')
    op.drop_table('menu_item')
    op.drop_table('restaurant')
    op.drop_table('app_user')
    # ### end Alembic commands ###
